opt_in_rules: # some rules are only opt-in
line_length: 200
disabled_rules:
  - control_statement
  - trailing_whitespace
  - cyclomatic_complexity
  - identifier_name
  - shorthand_operator
  - multiple_closures_with_trailing_closure
excluded:
  - Pods
  - app29cm-swift/Libraries
file_length:
  warning: 700
  error: 1200
function_body_length:
  - 100 # warning
  - 160 # error
type_body_length:
  - 400 # warning
  - 500 # error
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
