name: Swift

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
          pod update
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Build App
      run: xcodebuild -workspace "GiphyList.xcworkspace" -scheme "GiphyList" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
