name: Swift

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Dependencies
      run: |
          pod update
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
