name: Swift

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        cd Example
        pod install --repo-update
      shell: bash
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
